### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by palmskog** [rocq-community/fav-ssr#20]
I don't see any indication of a license for this project. Since the functions verified are inherently general and useful, it would enable others to reuse them if there was a free software / open source license. See [here](https://github.com/coq-community/manifesto/?tab=readme-ov-file#best-practices) for general recommendations about licensing.

**Comment by clayrat** [comment]
Added in https://github.com/clayrat/fav-ssr/commit/dee0a044b85e62a71a15b052d4b42580cd837e3c
