### ISSUE TITLE
Joining Coq-community?

### ISSUE THREAD

**Issue by palmskog** [rocq-community/fav-ssr#21]
This is a very valuable project for the community around Coq in that it shows fundamental applications of Coq for formalizing data structures and their operations, and in particular is a good showcase of using MathComp/SSReflect.

To allow the project to potentially reach a larger audience and ensure its maintenance over time, how about moving the repository to [Coq-community](https://github.com/coq-community)? Some immediate benefits include help with #19 and potentiallly joining MathComp's CI to receive updates as MathComp evolves. Nothing needs to change in terms of repository administration.

If that sounds reasonable, let me know and I can facilitate the process of joining Coq-community, which is described [here](https://github.com/coq-community/manifesto/blob/master/CONTRIBUTING.md#proposing-a-new-package).

**Comment by clayrat** [comment]
Yeah that sounds like a good idea, I want to finish porting the new quadtree chapter for now, but I guess we can also do this in parallel.

**Comment by clayrat** [comment]
> a good showcase of using MathComp/SSReflect

`Equations` too perhaps :)
